name: Appium Test

on:
  push:
    branches:
      - main # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
            java-version: '17'
            distribution: 'temurin'

      - name: Install App Center CLI
        run: npm install -g appcenter-cli

      - name: Authenticate with App Center
        run: appcenter login --token "4f87c6007841d1d490d28d75d4455f7df688f831"

      - name: Build and Test with Maven
        run: mvn -DskipTests -P prepare-for-upload package

      - name: Run Appium Tests on App Center
        run: |
            appcenter test run appium \
              --app "1999rahul.py-gmail.com/Test-App-2" \
              --devices "1999rahul.py-gmail.com/test" \
              --app-path ${{ github.workspace }}/app-release.apk \
              --test-series "master" \
              --locale "en_US" \
              --build-dir target/upload